# POKY_BBLAYERS_CONF_VERSION is increased each time build/conf/bblayers.conf
# changes incompatibly
POKY_BBLAYERS_CONF_VERSION = "2"

BBPATH = "${TOPDIR}"
BBFILES ?= ""

BBLAYERS ?= " \
  /home/tdieney/workspace/yocto-rpi5/poky/meta \
  /home/tdieney/workspace/yocto-rpi5/poky/meta-poky \
  /home/tdieney/workspace/yocto-rpi5/poky/meta-yocto-bsp \
  /home/tdieney/workspace/yocto-rpi5/poky/meta-openembedded/meta-oe \
  /home/tdieney/workspace/yocto-rpi5/poky/meta-openembedded/meta-python \
  /home/tdieney/workspace/yocto-rpi5/poky/meta-openembedded/meta-networking \
  /home/tdieney/workspace/yocto-rpi5/poky/meta-raspberrypi \
  /home/tdieney/workspace/yocto-rpi5/poky/build/workspace \
  /home/tdieney/workspace/yocto-rpi5/poky/meta-tdieney \
  /home/tdieney/workspace/yocto-rpi5/poky/meta-qt5 \
  /home/tdieney/workspace/yocto-rpi5/poky/meta-lts-mixins \
  "
